/**
 * Derives the site's theme CSS from the design contracts:
 * design-reference/contracts/tokens.js (type, mono, spacing, heights, radii,
 * breakpoints, measures) and the T1 table (colour). Nothing here is a value;
 * every number and colour comes from those two sources.
 *
 * The output is src/styles/theme.generated.css (`npm run theme`). It holds:
 *  - tokens.js's own CSS_VARS, verbatim;
 *  - T1 light values on :root, dark values under prefers-color-scheme, and
 *    the dark column again as a `[data-ground="ink"]` scope for ink blocks
 *    on a light page (the Call card);
 *  - a Tailwind v4 theme that resets every default (`--*: initial`) and
 *    re-adds only the tokens, so a stray `text-sm` or `bg-red-500` doesn't
 *    exist;
 *  - one utility per type step carrying family, size, line-height, tracking
 *    and case together, because tracking is a function of size (tokens.js
 *    law 1).
 */
import { FONT_FILES, fontFaceCss, type FamilyKey } from "./fonts.ts";
import type { T1Pair } from "./t1.ts";

export interface TypeStep {
  family: string;
  size: number;
  lineHeight: number;
  tracking: number;
  transform: string;
  weight?: number;
}

export interface Tokens {
  FAMILY: Record<string, string>;
  WEIGHT: Record<string, number>;
  TYPE: Record<string, TypeStep>;
  MONO: Record<string, TypeStep>;
  SPACE: Record<string, number>;
  HEIGHT: Record<string, number>;
  RADIUS: Record<string, number>;
  BREAKPOINT: Record<string, number>;
  MEASURE: Record<string, number>;
  CSS_VARS: string;
}

const HEADER = `/*
 * GENERATED by scripts/generate-theme.ts. Do not edit.
 * Sources: design-reference/contracts/tokens.js and the T1 table in
 * design-reference/boards/Theme.dc.html. Run \`npm run theme\` to rebuild;
 * test/theme.test.ts fails if this file and its sources disagree.
 */`;

const name = (token: string) => token.replace(/^--/, "");

function block(selector: string, lines: string[]): string {
  return `${selector} {\n${lines.map((line) => `  ${line}`).join("\n")}\n}`;
}

function colourVars(pairs: T1Pair[], side: "light" | "dark"): string[] {
  return pairs.map((pair) => `${pair.token}: ${pair[side]};`);
}

function typeUtility(
  prefix: string,
  key: string,
  step: TypeStep,
  weights: Record<string, number>,
): string {
  const lines = [
    `font-family: var(--font-${step.family});`,
    `font-size: ${String(step.size)}px;`,
    `line-height: ${String(step.lineHeight)};`,
    `letter-spacing: var(--track-${prefix === "type" ? key : `mono-${key}`});`,
    `text-transform: ${step.transform};`,
  ];
  const weight = step.family === "display" ? weights.black : step.weight;
  if (weight !== undefined) lines.push(`font-weight: ${String(weight)};`);
  return block(`@utility ${prefix}-${key}`, lines);
}

export function deriveThemeCss(tokens: Tokens, pairs: T1Pair[]): string {
  const px = (value: number) => `${String(value)}px`;
  // Literal values, not var() references: Tailwind's --font-* and --radius-*
  // names are the same as tokens.js's own variables, and `--x: var(--x)` is
  // a cycle. Colour is the exception: it must stay a reference so the
  // prefers-color-scheme and ink-scope values reach every utility.
  const theme = [
    "--*: initial;",
    ...Object.entries(tokens.FAMILY).map(
      ([key, value]) => `--font-${key}: ${value};`,
    ),
    ...Object.entries(tokens.WEIGHT)
      .filter(([key]) => key !== "black")
      .map(([key, value]) => `--font-weight-${key}: ${String(value)};`),
    ...pairs.map((pair) => `--color-${name(pair.token)}: var(${pair.token});`),
    ...Object.entries(tokens.SPACE).map(
      ([key, value]) => `--spacing-${key}: ${px(value)};`,
    ),
    ...Object.entries(tokens.HEIGHT).map(
      ([key, value]) => `--spacing-${key}: ${px(value)};`,
    ),
    ...Object.entries(tokens.RADIUS).map(
      ([key, value]) => `--radius-${key}: ${px(value)};`,
    ),
    ...Object.entries(tokens.BREAKPOINT).map(
      ([key, value]) => `--breakpoint-${key}: ${px(value)};`,
    ),
    ...Object.entries(tokens.MEASURE).map(
      ([key, value]) => `--container-${key}: ${px(value)};`,
    ),
  ];

  return (
    [
      HEADER,
      tokens.CSS_VARS,
      block(":root", [
        "color-scheme: light dark;",
        ...colourVars(pairs, "light"),
      ]),
      `@media (prefers-color-scheme: dark) {\n${block(
        ":root",
        colourVars(pairs, "dark"),
      )
        .split("\n")
        .map((line) => `  ${line}`)
        .join("\n")}\n}`,
      block('[data-ground="ink"]', [
        "color-scheme: dark;",
        ...colourVars(pairs, "dark"),
      ]),
      block("@theme inline", theme),
      ...Object.entries(tokens.TYPE).map(([key, step]) =>
        typeUtility("type", key, step, tokens.WEIGHT),
      ),
      ...Object.entries(tokens.MONO).map(([key, step]) =>
        typeUtility("mono", key, step, tokens.WEIGHT),
      ),
    ].join("\n\n") + "\n"
  );
}

export function deriveFontsCss(tokens: Tokens, urlBase: string): string {
  const family = tokens.FAMILY as Record<FamilyKey, string>;
  const header = HEADER.replace(
    "Sources: design-reference/contracts/tokens.js and the T1 table in\n * design-reference/boards/Theme.dc.html.",
    "Sources: src/theme/fonts.ts, with family names from\n * design-reference/contracts/tokens.js FAMILY.",
  );
  return `${header}\n\n${fontFaceCss(FONT_FILES, family, urlBase)}\n`;
}
